### ISSUE TITLE
Check Google and Apple developer documents what it legally means to opt out of tracking

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-android#54]
I will look into that.

**Comment by AramZS** [comment]
I think the best tactic is a shared storage provided by the app that other apps can check. As long as it is a standard name, others can adopt and check it.

**Comment by n-aggarwal** [comment]
The Google Policy States the following:

>  ​​"Limit Ad Tracking" (LAT) lets users opt out and therefore restrict advertisers from targeting based on user behavior.
It is a requirement of Google and Google Marketing Platform policies to ensure that user choices are accurately adhered to when data is passed on ad requests. 

> Deleting AdId: Your advertising ID will be reset or deleted, but apps may have their own settings using other types of identifiers, which can also affect the types of ads you see.

This means that deleting the AdId may stop cross-ads identifying, but personalization based on in-app tracking may continue. This is different from GPC in the sense that GPC stops all ad related tracking activities; it is a universal do-not-sell instruction.

References: 
https://support.google.com/admanager/answer/6238701?hl=en
https://policies.google.com/technologies/ads

**Comment by kasnder** [comment]
> The Google Policy States the following:
> 
> > ​​"Limit Ad Tracking" (LAT) lets users opt out and therefore restrict advertisers from targeting based on user behavior.
> > It is a requirement of Google and Google Marketing Platform policies to ensure that user choices are accurately adhered to when data is passed on ad requests.
> 
> > Deleting AdId: Your advertising ID will be reset or deleted, but apps may have their own settings using other types of identifiers, which can also affect the types of ads you see.
> 
> This means that deleting the AdId may stop cross-ads identifying, but personalization based on in-app tracking may continue. This is different from GPC in the sense that GPC stops all ad related tracking activities; it is a universal do-not-sell instruction.
> 
> References: https://support.google.com/admanager/answer/6238701?hl=en https://policies.google.com/technologies/ads

That's a great find. Thank you!

**Comment by kasnder** [comment]
As a general point: A big contribution of our work will be explain how to configure things AND what they mean. We should be super careful and diligent in this task.

**Comment by n-aggarwal** [comment]
We have a clear understanding of what it means legally to opt out of tracking (Limit Ad Tracking/Delete Advertising Id) as per the Google developer documentation. Therefore, I am closing this issue.
