### ISSUE TITLE
Does the AdId deletion work?

### ISSUE THREAD

**Issue by n-aggarwal** [privacy-tech-lab/gpc-android#56]
Deleting AdId means that developers cannot query that value anymore; however, there is a possibility that the apps store the AdId in storage and still continue using it. To check whether this happens or not, I will download 10 apps from different categories, apply apk-mitm on them and then observe the traffic. 

The process will be as follows: Initially. I will leave the AdId enabled and browse through the apps. Then after sufficient time has been spent, I will delete the Adid and then continue using the app, observing the network data using PCAPdroid to see if the app still passes the Adid.

Given below is the list of 10 apps I plan to install for this experiment:

Potential Apps to download:
| App Name | Category | Number of Users | 
| --- | --- | --- |
| Idle Miner Tycoon | Game | 100 Million + |		
| NewsBreak |	News |50 Million + |
| Spotify (been using from before) | Music | 1 Billion + |
| Picsart AI Photo Editor | Photo | 1 Billion + |
| Instagram (been using from before) | Social | 1 Billion + |
| Amazon Shopping | Shopping | 500 Million + |
| Yahoo Sports | Sports	| 10 Million + |
| The Weather Channel | Weather | 100 Million |
| Tubi | Entertainment | 100 Million + |

If you have any suggestions let me know.

**Comment by kasnder** [comment]
I would make sure to 'force quit' the app after deleting the AdId. Otherwise, this looks good!

**Comment by n-aggarwal** [comment]
Unfortunately I wasn't able to use the list of apps given above for this experiment because of various issues regarding installing the apps including the files being xapks, and mitm-proxy errors. So here is a list of updated apps that I now have: 

| App Name | Category | Number of Users | 
| --- | --- | --- |
| Cut the Rope | Game | 100 Million + |		
| NewsBreak |	News | 50 Million + |
| iHeartRadio | Music | 50 Milllion + |
| PowerDirector -Video Editor | Photo | 100 Million + |
| Amazon Shopping | Shopping | 500 Million + |
| Fox Sports | Sports | 10 Million + |
| The Weather Channel | Weather | 100 Million + |
| Twitch | Entertainment | 100 Million + |

I wasn't able to find an app in the social category that would work. Most of them threw errors when running apk-mitm. The only one I was successfully able to complete apk-mitm on was Facebook lite, but even after I downloaded I was unable to access the network data. One possible reason for this from what I read could be certificate pinning. Is there any easy way around that ?

**Comment by n-aggarwal** [comment]
I have the AdId turned on as of right now and I can see the network data. But there are a Lot of different packets being sent around to and from the app. As of right now I am unable to see where and when the app is transmitting the AdId. I have attached screenshot of what it looks like on my phone: 

<img src = https://user-images.githubusercontent.com/121606501/234132167-f729786b-1c7d-4737-9f59-897470bd2578.png alt = "frontpage" width = 280  height = 560> <img src = https://user-images.githubusercontent.com/121606501/234132654-bfd3bbeb-a3ad-4a77-9725-27a2648b2fae.png alt = "All App Activity" width = 280  height = 560>
<img src = https://user-images.githubusercontent.com/121606501/234133037-340936b0-028a-4d25-b209-e0dff285bf5e.png alt = "One of the Network Conversations" width = 280  height = 560> <img src = https://user-images.githubusercontent.com/121606501/234133122-66b032aa-3696-43c1-a225-30135f120746.png alt = "Another one of the Network Conversations" width = 280  height = 560>

I am unsure of which network requests I need to look at and where exactly the AdId would be in the requests.

**Comment by kasnder** [comment]
This is a great start! I'm glad you've been able to look into some request. @n-aggarwal

As far as I recall, there's an option in that app to export network traffic. This could then be analysed on a computer.

Alternatively, it's probably good to set up a running version of `mitmproxy`. There are plenty of tutorials online to get you started on this one.

**Comment by n-aggarwal** [comment]
I was able to get the PCAPdroid data into Wireshark and decrypt it.

To get the data into Wireshark, I used the command: ` curl -NLs http://172.21.77.100:8080 | wireshark -k -i -` where `172.21.77.100:8080` is the server/port provided by PCAPdroid. Additionally, I have to be on the same local network as the device running PCAPdroid. 

This should enable you to see the packets being captured In Wireshark. Once you stop the capture, PCAPdroid provides me with a `sslkeylog.txt` file that I can use to decrypt the data. To do so first find a packages with TLS encryption, `right click on it > protocol preferences > Transport Layer Security > (Pre)-Master-Secret log filename: ` and then choose the `sslkeylog.txt` file.

Finally, to only see the http requests we can filter the packets in Wireshark by the following command: `http or http2`. This gives me all the http  (decrypted) packages that our app sent/recieved. 

Now the problem has reduced to learning to use Wireshark. I will try and get familiar with it over the next week.

**Comment by n-aggarwal** [comment]
I was able to get the data to Application level in Wireshark and then analyze it. There are a couple of steps involved to do this:
1. Download the [pcapdroid.lua plugin](https://github.com/emanuele-f/PCAPdroid/blob/master/tools/pcapdroid.lua) for wireshark. 
2. Create a directory for custom plugins in Wireshark. `open Wireshark  > About Wireshark > Folders > Personal Lua Plugins`. Double click on the `Personal Lua Plugins` and it will ask you if you want to create a new folder; yes, and then navigate to it (double clicking it again opens the folder).
3. Install the plugin into that directory
4. `Analyze > Reload Lua Plugins` or restart Wireshark to activate the installed plugin.
5. import the pcapng file and decrypt it using the `sslkeylog.txt` file as described above.
6. Now filter to see only `http or http2` packets
7. Now if you look at one of the packets it will contain a `Pcapdroid` Section. Expand that section and there will be a `App Name` field. Drag this to the top of wireshark and make it a new column. 
8. Now all the packets will have an app associated with them. 
9. To perform AdId Analysis now, go `Edit > Find Packet` change `display filter` to `string` and search for the AdId. 

Here are a few screenshots of what it looks like:
<img width="1440" alt="Screenshot 2023-05-22 at 10 15 21 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/0237c464-3a67-4fe4-b4a3-fa27ceefc9cc">
<img width="1440" alt="Screenshot 2023-05-22 at 9 56 55 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/38957bf7-c035-402a-bcc0-bf41242aa8e4">

**Comment by kasnder** [comment]
Cool stuff. Fantastic work!

**Comment by n-aggarwal** [comment]
Today, I captured the Network data of the apps with the AdId enabled. Most of the results were as expected but there were a few interesting things. I have attached screenshots below to share my findings:

Key:
 - Red: Expected
 - Yellow: Unexpected

For reference my adid is: 4a5c227e-24b6-45fc-8efb-c780ce34af24

### Cut the Rope
<img width="1440" alt="Screenshot 2023-06-02 at 11 51 43 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/92a17819-c33b-4f8f-8f2f-86171eaea60b" >
<br />
Nothing special going on here.

### Fox Sports

<img width="1440" alt="Screenshot 2023-06-02 at 11 57 22 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/1329cb6b-de63-4b08-8e4f-f2ed26330c1b">

Now that I am looking at this a second time, I see that the app did fingerprint my device.  This can be seen in the  third header field from the top. 

### Amazon Shopping
<img width="1440" alt="Screenshot 2023-06-03 at 12 00 35 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/982f87ab-13e0-44cc-8105-62e1349aea10">

This one is very interesting in my opinion. My adid is tagged as "idfa" which is the IOS name for adid, but then there is an additional "adid". This "adid" might be another Advertising identifier! Additionally, in the middle of both of those, there is also an "appid". I am not sure what this is used for, but this seems to be another unique identifier.

### Newsbreak
<img width="1440" alt="Screenshot 2023-06-03 at 12 07 23 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/542a745c-ba43-4def-b2f5-6cac82a6f7ed">

Again nothing particularly interesting going on here.

### Power director 
<img width="1440" alt="Screenshot 2023-06-03 at 12 11 04 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/4c140165-980f-4208-999d-c8ea6decaeaa">

This app doesn't use the AdId at all! In fact, if you look carefully it doesn't even use internet a lot; less than 1% of the packets were `http or http2` compared to 15% to 25% for most other apps! Probably not a good choice to test.

### iHeart Radio
<img width="1440" alt="Screenshot 2023-06-03 at 12 14 42 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/15b610f0-b9fb-4260-a5b9-4f283ae660a7">

This one is rather interesting. Along with the adId (sessioId) there is a profileId and a deviceId. These may be being used for tracking purposes.

### Twitch
<img width="1440" alt="Screenshot 2023-06-03 at 12 20 04 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/4a85ec77-c4d3-4fd5-8b45-b03711ac976d">
<img width="1440" alt="Screenshot 2023-06-03 at 12 21 41 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/a6d6d686-036a-41fe-bde3-00f4c912bf45">

Twitch is also interesting! It doesn't use the adid but has a bunch of unique identifiers. Additionally it also has a sessionId; it probably isn't something to worry about, but some apps store the adid as sessionId, so I started wondering if Twitch used the sessionId for Tracking.

### The Weather Channel

<img width="1440" alt="Screenshot 2023-06-03 at 12 25 01 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/02377ccc-dc4e-4591-a251-c1df616f87ac">
<img width="1440" alt="Screenshot 2023-06-03 at 12 26 07 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/4f858fad-d46c-4cb2-90aa-74f4b359824f">

This app uses the adId and also collects information about my device that my be used to uniquely identify me. 

### Next Steps

This is a preliminary overview of what was going on. I will take a look at the data again once tomorrow to see if I missed anything. I will then delete my AdId and see what happens.

**Comment by n-aggarwal** [comment]
I have now deleted my adId and ran a new PCAPdroid capture for 6 of the apps: 
1. Cut the Rope
2. Fox Sports
3. The Weather Channel
4. Newsbreak
5. Amazon Shopping
6. iHeart Radio

I didn't capture data for Twitch or PowerDirector because even before I deleted the AdId, they weren't using it.

### Cut the Rope
<img width="1440" alt="Screenshot 2023-06-05 at 4 16 44 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/5f571d5a-ced9-4b89-96d1-45f887048518">

The AdId is now zeroed out as expected. Nothing too interesting going on here.

### Fox Sports
<img width="1440" alt="Screenshot 2023-06-05 at 4 50 11 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/fa919e6d-ef7e-4bf7-8d77-d0c59c986c48">

The AdId is still being sent!! Interestingly enough, it is being stored as a cookie somehow; I am not sure how that works.

### The Weather Channel

<img width="1440" alt="Screenshot 2023-06-05 at 7 26 51 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/b20a22bc-714d-4942-8ddb-1546743bbd47">

Again, the AdId is still being sent, and once again, it is being stored as a cookie somehow.

### Newsbreak

<img width="1440" alt="Screenshot 2023-06-05 at 6 28 13 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/1057b338-276e-4ebf-9933-bc910c27f893">

Again, the adId is being sent!

### Amazon Shopping

<img width="1440" alt="Screenshot 2023-06-05 at 4 34 04 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/e46952f7-8295-40f3-9c7d-43ea7a3d1187">

Amazon does a good job! Not only does it zero out the "idfa" but it also stops using the "adid"!

### iHeart Radio

<img width="1440" alt="Screenshot 2023-06-05 at 7 09 52 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/320f6677-a3c4-4434-b614-ae0cab50be27">

iHeartRadio does zero out the adId but notice there are a bunch of other id's that are still being sent! Although, we can't know for sure, it is very possible that one of these is being used for ad tracking purposes.

### Conclusions

It seems that even after the AdId is deleted, the apps are still storing it locally as a cookie, and using it! This makes me wonder what would happen I reset the Adid and then delete It? Would that be better for user privacy? Furthermore, is this even legal by the Google developer agreement?

**Comment by n-aggarwal** [comment]
So, next I tried to force quit Newsbreak, Fox Sports, and The Weather Channel apps (the ones that were still using the adId), and after I did, the AdId was not in the capture for the Weather Channel, and Fox Sports, but unfortunately was still present in Newsbreak.

**Comment by n-aggarwal** [comment]
So Newsbreak does something interesting. It in fact turns out that it stopped using my Adid for ad purposes as soon as deleted it, but it continues using that string for other purposes. Here is a screenshot of the capture after I got the new AdID:

<img width="1440" alt="Screenshot 2023-06-05 at 11 07 44 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/e5546a91-62af-468d-be44-a0a5e59b1501">

As it can been above, my previous ID is still being used for something, but now the new AdID is also there as "aaid". So, now if I go to the previous capture where I had just deleted the AdID (no force quit), it can be seen the field "aaid" is zeroed out.

<img width="1440" alt="Screenshot 2023-06-05 at 11 09 03 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/c45f6458-ff63-439f-ac8e-a85effd08a94">

As such, it seems that the old adId is not being used for Ad Tracking purposes but for something else, although we can not be sure of this.

**Comment by n-aggarwal** [comment]
The preliminary exploration is now complete; we have an idea of the sort of data we might see, and the changes that may or may not happen from deleting the adId. As such, I am closing this issue. If anything new comes up, I can reopen it if needed.
