### ISSUE TITLE
Add instructions for adding browser with support for GPC signal

### ISSUE THREAD

**Issue by n-aggarwal** [privacy-tech-lab/gpc-android#57]
The easiest way to stop any and all tracking through browsers is by attaching a GPC signal. Unfortunately, doing so without root access can be extremely difficult to implement, if at all possible. An easier solution would be to instruct users to download a browser that has built in GPC support.

The first step is to check which browsers have built-in GPC support; some potential browsers are: Bromite, DuckDuckGo, Brave, Firefox, Tor. 

The second step would be to explain to the user that they need to download one of these browsers and use that one instead of the system browser; the explanation should be short, and easy to understand in order to increase usability.

Finally, the third step would be to integrate a button that redirects the user to the play store to the page where they can download the browser.

**Comment by wesley-tan** [comment]
https://docs.google.com/document/d/1WeDitLL1oMSsGKgiSXuPSyEBH7A7MyJYhF3oQ6dSG9s/edit?usp=sharing
will update code
