### ISSUE TITLE
Determine minimum SDK version of the app

### ISSUE THREAD

**Issue by n-aggarwal** [privacy-tech-lab/gpc-android#60]
Find the minimum sdk version that our app would be compatible with to maximize the percentage of audience that we can reach.

**Comment by SebastianZimmeck** [comment]
> The minimum SDK version of the app could be API 21; this is Android 5.0.

This sounds good to me.

**Comment by SebastianZimmeck** [comment]
I think we settled on Android 5 (API 21). So feel free to close if there is nothing more to do, @n-aggarwal.

**Comment by n-aggarwal** [comment]
I will create a new branch and change the minimum SDK version of the app. Then I will open a PR and once that is merged we can close this issue.

**Comment by wesley-tan** [comment]
Believe that this can be closed; min sdk version API 21

**Comment by SebastianZimmeck** [comment]
I reopened this issue because there is still a linked [PR](https://github.com/privacy-tech-lab/gpc-android/issues/60#event-9204408669) open. Once that is merged, please feel free to close again @wesley-tan.
