### ISSUE TITLE
Explore availability and functionalities of "privacy advice" apps on Android

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-android#62]
Our goal is to bring GPC to Android. Our current approach is to advise users of app settings that will effectively enable GPC on Android. In a broader sense, we provide a privacy advice app (at least as ad tracking is concerned). This is an interesting concept. Would users like such an app, find it useful, ...? That is a direction we could go into. 

So, the question is, are there already other privacy advice apps? If so, which functionalities do they provide? As @wesley-tan mentioned in our call today, we should look into user-facing apps and also consider SDKs, notably, those provided by consent management platforms (CMPs) like [OneTrust](https://www.onetrust.com/products/mobile-app-consent/). We may not be able to get their code, but still it would be important to understand as much as we can. Other CMPs are Complianz, TrustArc, SourcePoint, Didomi, Wirewheel, ... And then, are there user-facing privacy advice apps on the Play Store?

@wesley-tan will take the lead on this issue and @n-aggarwal will help out as necessary.

**Comment by n-aggarwal** [comment]
I downloaded and looked at a couple of top privacy apps on Play Store including:
|App|Number of Downloads|
|-------------|----------------------|
|IronVest|100,000+|
|Privacy Defender| 50,000+|
|Privacy Dashboard| 100,000+|
|MyPrivacy|100,000+|
|Private Zone|1,000,000+|
|Privacy Scanner| 500,000+|
|Protect My Privacy| 5,000+|
|Avast One|100,000+|
|Privacy Master| 1,000,000+|

Most of these apps have some or all of the features listed below (The bolded features were more common across apps):
- Firewall
- Malware Protection
- <b>Secure Vault (Hiding photos, files and/or contacts) </b>
- App Permissions detector + usage
- Anonymous Browser
- <b>App locking</b>
- Masked Email
- <b>Password Manager </b>
- Ram Cleaner

The one app which looks interesting and may have potential is Protect My Privacy. In particular it has a feature called protect my digital footprint which essentially searches for companies which may have your data, and then presents you with 3 options in accordance with the GDPR as shown in the screenshots below. Unfortunately I wasn’t able to get the app working as of now.  
<img src = "https://github.com/privacy-tech-lab/gpc-android/assets/121606501/f1a65d76-761a-43b6-855d-16433f66cf82" width= 340 height= 640/> <img src= "https://github.com/privacy-tech-lab/gpc-android/assets/121606501/45a95f9f-4e8c-472c-875e-cdd3d2141b02" width = 340 height=640/>
(Sorry about the first image quality- the app had anti-screenshot functionality)


So, the way I see it, if we publish a “privacy advice” app on the play store, the main problem we would face is that we would need to differentiate ourselves from all these other apps. Moreover, when people search for privacy apps, they might not want what we are offering but instead more of the other features listed above.

**Comment by wesley-tan** [comment]
On that note, I think this is both good and bad because it suggests the following
1. What is typically associated with privacy seems to be quite different from the app we are proposing. This means that we may be covering ground that other apps do not
2. But this also may mean that users perhaps may not value such a privacy advice app. 
Have been bogged down by exams this week but I will look into the further in the coming week. This is tangential but one thing that is interesting relates to the privacy labels on Google Play. Basically, many of the labels on the Play store itself may be misleading.
https://www.theverge.com/2023/2/23/23612009/google-play-android-apps-privacy-false-misleading-mozilla-study

**Comment by wesley-tan** [comment]
Compiling my thoughts here regarding workflow, existing apps etc (https://docs.google.com/document/d/1Be53srG1lVe-XujykA0AOfLY-Epdf9extInS_-vZNNE/edit?usp=sharing)
