### ISSUE TITLE
Add GPC header to mobile requests with `mitmproxy`

### ISSUE THREAD

**Issue by kasnder** [privacy-tech-lab/gpc-android#64]
Explore use of `mitmproxy`. Example: <https://github.com/mitmproxy/mitmproxy/discussions/5155>

**Comment by n-aggarwal** [comment]
I was able to successfully add the GPC header to all requests being sent. The process is very similar to the instructions for setting up mitmproxy wireguard. The only difference is that now I added a python script that instructed mitm to add the GPC header to every outgoing request. The terminal command now is `mitmweb --mode wireguard -s mitm-script.py` where `mitm-script.py` is the name of the script file.

Below is a screenshot of what the requests look like now:
<img width="1440" alt="Screenshot 2023-05-30 at 4 37 45 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/9c2565af-c5d2-45ba-a662-ee5f574c13d9">

I will create an associated branch with the issue and push the python script on that branch.

**Comment by kasnder** [comment]
Amazing stuff!!!!!

**Comment by SebastianZimmeck** [comment]
Excellent! So, now the question is how we can use this instrumentation to inject GPC into a larger set of apps.

**Comment by SebastianZimmeck** [comment]
But, maybe, that is a different issue. So, @n-aggarwal, please feel free to manage this as you see fit.

**Comment by n-aggarwal** [comment]
Since I was successfully able to add GPC header to mobile requests with mitmproxy, I am going to this issue. The script file to add the GPC flag is in branch [issue-64](https://github.com/privacy-tech-lab/gpc-android/tree/issue-64).

**Comment by SebastianZimmeck** [comment]
> The script file to add the GPC flag is in branch [issue-64](https://github.com/privacy-tech-lab/gpc-android/tree/issue-64).

I'd say, add it to the main branch of the repo, e.g, in a scripts directory.
