### ISSUE TITLE
Set up `mitmproxy`

### ISSUE THREAD

**Issue by kasnder** [privacy-tech-lab/gpc-android#65]
First do this, then address #64

**Comment by kasnder** [comment]
Explore Wireguard mode for this: <https://docs.mitmproxy.org/stable/concepts-modes/#wireguard-transparent-proxy>

**Comment by kasnder** [comment]
More explanation here: https://mitmproxy.org/posts/wireguard-mode/

**Comment by n-aggarwal** [comment]
I was able to setup the mitmproxy with WireGuard to intercept the network traffic from android. To do so:

1. The user must first download the WireGuard app on the Phone through play store. 
2. Next, run the command `mitmweb --mode wireguard` in the terminal. Note this step assumes that mitmproxy has been installed and configured correctly on the users device.
3. Now a new tab should open in your browser; this will contain a QR code. Scan the QR code using the WireGuard app you installed on your phone and save it.
4. Now you can turn on this vpn tunnel in the WireGuard app, and all the traffic should be intercepted!

Note: I also had the mitmproxy certificate installed on my phone. If the above steps cause encryption/decryption errors that might be the issue. Make sure the certificate is of type `.crt` before installing it on Android.
