### ISSUE TITLE
Define research milestones in GitHub projects

### ISSUE THREAD

**Issue by kasnder** [privacy-tech-lab/gpc-android#67]
See examples at the top of this document: https://docs.google.com/document/d/1Be53srG1lVe-XujykA0AOfLY-Epdf9extInS_-vZNNE/edit

**Comment by wesley-tan** [comment]
We should discuss this further during the meeting, but our rough milestones (assuming the Nov deadline) could look something like

Deciding on research questions (needs to be done asap) - by end June
At the moment, the research question is shaping up to be something like "How does the AdID and GPC signal affect the network traffic?"
- What happens to the AdID etc? 
- Any other unique AdIDs (e.g. Facebook, Amazon) 
- Usability study component

Deciding on research studies & methdology (e.g. usability / measurement) - by end June
Measurement of top 1000 apps
- Without Android setting
- With Android setting
- With GPC signal (header)
- Without GPC signal (header)
and how to automate this process

Finish measurement and testing - end July
Analysis of top 1000 apps

Usability study  - by mid-Aug
Conduct a survey that gathers information on…
- how people perceive and react to different ad tracking prompts
- evaluates their understanding of the ad ecosystem and ad tracking

Writing up (about 2–2.5 months) - mid-Aug to Nov

**Comment by SebastianZimmeck** [comment]
That is a good plan, @wesley-tan!

**Comment by wesley-tan** [comment]
Have written out milestones under Issues, we can update it as the project moves along. We can discuss this further later

**Comment by wesley-tan** [comment]
Will use Github milestones moving forward.
