### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-android#72]
We should begin documenting what is contained in the repo and how to use it (e.g., setup and install instructions).

Here are some example readmes (though, ours will be far shorter initially): 
- [OptMeowt](https://github.com/privacy-tech-lab/gpc-optmeowt)
- [Privacy Pioneer](https://github.com/privacy-tech-lab/privacy-pioneer)

**Comment by wesley-tan** [comment]
Have written and committed a draft, will be updating further!

**Comment by wesley-tan** [comment]
Updated and made it clearer; moving forward, think a good way to update this as we develop our methodology is perhaps to review the README perhaps monthly to ensure it is updated?

**Comment by n-aggarwal** [comment]
Note to self:

Update readme to include high level descriptions of the automation scripts, and the procedure to use them.

**Comment by SebastianZimmeck** [comment]
I will revise the readme a bit.

**Comment by SebastianZimmeck** [comment]
I revised the readme. @wesley-tan and @n-aggarwal, please take a close look. If anything is unclear or incorrect, whether on text you wrote or someone else, please point it out here or correct it straight. In particular, the following is unclear to me. Please clarify these points in the readme:

> Download the WireGuard app to your phone through the Google Play Store.

At a minimum, let's include a link to the WireGuard app. Possibly, even include how to install it if this is difficult (or at least of the salient steps).

> Note this step assumes that mitmproxy has been installed and configured correctly on the phone

Same comment here, at least a link to the install instructions of mitmproxy and possibly more explanations on installing it.

> VPN tunnel in the WireGuard app

Link to VPN tunnel or screenshot?

> Use [apk-mitm](https://github.com/shroudedcode/apk-mitm) on the APK.

Same comment here, at least a link to apk-mitm and possibly more explanations on installing it.

> which is used to scrape app data from the Google Play Store

What kind of data? APKs, metadata, both? If metadata, all metadata from Play Store pages. I do not think we need to give all details here, but at least a sense of which data we are talking about.

> To scrape app metadata from the Google Play Store

"app metadata" correct?

> Download APKs from the Google Play Store with

"APKs" correct?

> Then, give the script execution permissions and run it.

What exactly does that mean? What should be the `chmod`? Or is this done through the UI? How does one "give the script execution permissions"?

@kasnder, feel free to let me know any changes, additions, logos, etc. you would like. I am flexible.

**Comment by n-aggarwal** [comment]
We are not using the Wireguard mode anymore for the proxy. We have switched over to SOCKS5 mode. As such, the Readme needs to be updated to reflect the same. I can update that by our next meeting.

**Comment by SebastianZimmeck** [comment]
Sounds good!

**Comment by SebastianZimmeck** [comment]
@n-aggarwal updated the readme already.

**Comment by SebastianZimmeck** [comment]
I am closing this issue for the time being. We can open a new one if the readme concretely requires an update.
