### ISSUE TITLE
Running Mitm/Har network captures

### ISSUE THREAD

**Issue by n-aggarwal** [privacy-tech-lab/gpc-android#85]
I am opening this issue to document problems that come along as I am collecting data, and to keep track of progress.

**Comment by n-aggarwal** [comment]
I am running quite a bit behind schedule.The reason for that is that not all the captures are running properly. In a folder of about 45 apps, I am finding only 35 work. Then I have to manually go through the rest of the 10 to find out what went wrong. 

The way I am telling if something went wrong is if the “har” file is in bytes, or the “mitm” file is around 11kb for several captures of the app. This is the usual traffic that is captured without running any app. Sometimes, the case is simply that the app does not transmit data, but most of the times it means the apk was not installed properly. 

I have found several main reasons for these apks not being installed correctly:
1. There is a split apk folder and a normal apk for the same app. My code by default looks for the apk, and usually this leads to problems. This one can be fixed by making split apks the default. <img width="895" alt="Screenshot 2023-08-17 at 9 16 46 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/fd9b1b24-0280-4d09-9f20-d9dd17694ce6">
2. Sometimes, inside a split apk folder, there are duplicates of the same config files, say “v8a”, and these cause installation problems (notice how the duplicates have different dates as well). Additionally, as can been seen in the screenshots below, there are some stray files with no extension. I have no idea what role these play. <img width="676" alt="Screenshot 2023-08-18 at 2 49 19 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/f854bbcd-7e7d-4560-9114-39f441bacbab"> <img width="893" alt="Screenshot 2023-08-17 at 9 16 08 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/121606501/42f9c989-dc84-4079-9b31-86a2d8b79eba">


3.  The third problem is that sometime the apks are entirely missing even though the set should be full. Ex. “com.catdaddy.nba2kmcom.ea.tsb” in “GAME_SPORTS”.

The above mentioned are the frequently occurring problems.

 Apart from these, I once saw an xapk, but that may just be a one off. Nevertheless, we need to take care of these problems ASAP for the captures to run efficiently.

**Comment by n-aggarwal** [comment]
To save time, I propose an alternative. Instead of me looking into what went wrong for each app that didn't work. I will simply note the apps that failed in the "app_fail.txt" file. Then over the course of the next two weeks @wesley-tan can look at those apks and fix them, re-download them, or whatever else needs to be done. Then I can run those apps that are left.

**Comment by n-aggarwal** [comment]
In this case @wesley-tan should only spend a few minutes on each of the apks that failed. If he can't figure out the issue, then he can simply move on. I will take care of that. His work would be to fix the majority of the apks which fall under one of the 3 categories above. If he can't find the issue, then I will take a look at it.

**Comment by SebastianZimmeck** [comment]
OK, let's do that.

**Comment by SebastianZimmeck** [comment]
Here are the current issues: 

- [ ] Empty folders
- [ ] APK and Split APKs for the same app
- [ ] Duplicate APKs in the split APK folder
- [ ] Few missing APKs (maybe Google Drive upload/download) issue

@wesley-tan is in the lead on fixing the above. Please update @n-aggarwal and @wesley-tan as needed.

**Comment by SebastianZimmeck** [comment]
Closing since we have the [new issue](https://github.com/privacy-tech-lab/gpc-android-paper/issues/8) on a more specific point.
